import 'package:easy_localization/easy_localization.dart';

class ManagerStrings {
  static String get appName => tr('appName');
  static String get completeProfileAppBarTitle => tr('completeProfileAppBarTitle');
  static String get noInternetErrorMessage => tr('noInternetErrorMessage');
  static String get serverFailureMessage => tr('serverFailureMessage');
  static String get emptyCacheFailureMessage => tr('serverFailureMessage');
  static String get offlineFailureMessage => tr('offlineFailureMessage');
  static String get notLoggedInFailureMessage => tr('notLoggedInFailureMessage');
  static String get notRegisteredFailureMessage => tr('notRegisteredFailureMessage');
  static String get notVerifiedFailureMessage => tr('notVerifiedFailureMessage');
  static String get registeredFailureMessage => tr('registeredFailureMessage');
  static String get checkCustomerAccountError => tr('checkCustomerAccountError');
  static String get verifyPhoneNumberError => tr('verifyPhoneNumberError');

  static String get login => tr('login');
  static String get loginButton => tr('loginButton');
  static String get phoneNumber => tr('phoneNumber');
  static String get loginHintText => tr('loginHintText');
  static String get loginViewText1 => tr('loginViewText1');
  static String get loginViewText2 => tr('loginViewText2');
  static String get loginViewText3 => tr('loginViewText3');
  static String get otpButtonText => tr('otpButtonText');
  static String get otpText1 => tr('otpText1');
  static String get otpText2 => tr('otpText2');
  static String get phoneVerifiedSuccess => tr('phoneVerifiedSuccess');
  static String get wrongVerificationId => tr('wrongVerificationId');
  static String get checkPhoneNumber => tr('checkPhoneNumber');

  static String get nullValue => tr('nullValue');
  static String get confirmLogoutDialogMessage => tr('confirmLogoutDialogMessage');
  static String get confirmLogout => tr('confirmLogout');
  static String get cancel => tr('cancel');
  static String get colors => tr('colors');
  static String get sizes => tr('sizes');
  static String get description => tr('description');
  static String get pay => tr('pay');

  static String get congrats => tr('congrats');
  static String get greatJob => tr('greatJob');
  static String get dataSaved => tr('dataSaved');

  static String get welcomeMessage => tr('welcomeMessage');
  static String get redirectMessage => tr('redirectMessage');
  static String get save => tr('save');
  static String get mainPage => tr('mainPage');
  static String get male => tr('male');
  static String get female => tr('female');
  static String get phoneNumberLabel => tr('phoneNumberLabel');
  static String get userNameLabel => tr('userNameLabel');
  static String get hintTextUserName => tr('hintTextUserName');
  static String get usernameValidationMessage => tr('usernameValidationMessage');
  static String get emailLabel => tr('emailLabel');
  static String get hintTextEmail => tr('hintTextEmail');
  static String get emailValidationMessage => tr('emailValidationMessage');
  static String get idNumberLabel => tr('idNumberLabel');
  static String get hintTextIdNumber => tr('hintTextIdNumber');
  static String get dayOfBirthLabel => tr('dayOfBirthLabel');
  static String get hintTextDayOfBirth => tr('hintTextDayOfBirth');
  static String get genderLabel => tr('genderLabel');

  static String get homePageTitle => tr('homePageTitle');
  static String get searchHint => tr('searchHint');
  static String get sliderTitle => tr('sliderTitle');
  static String get sliderSubTitle => tr('sliderSubTitle');
  static String get trend => tr('trend');
  static String get newProduct => tr('newProduct');
  static String get soon => tr('soon');
  static String get productTitle => tr('productTitle');
  static String get productCategory => tr('productCategory');
  static String get completeProfileUpdateSuccess => tr('completeProfileUpdateSuccess');
  static String get completeProfileUpdateFailed => tr('completeProfileUpdateFailed');
  static String get profilePageTitle => tr('profilePageTitle');
  static String get profilePersonalInfoPageTitle => tr('profilePersonalInfoPageTitle');
  static String get profileShareApp => tr('profileShareApp');
  static String get profileSupport => tr('profileSupport');
  static String get profileSettings => tr('profileSettings');
  static String get profileLogout => tr('profileLogout');
  static String get profileDeleteAccount => tr('profileDeleteAccount');
  static String get supportSheetTopText => tr('supportSheetTopText');
  static String get supportSheetBottomText => tr('supportSheetBottomText');
  static String get offers => tr('offers');
  static String get topSelling => tr('topSelling');
  static String get newProducts => tr('newProducts');
  static String get emptyProducts => tr('emptyProducts');
  static String get noQty => tr('noQty');
  static String get noSizes => tr('noSizes');
  static String get noColors => tr('noColors');
}